
[window]
startup_mode = "Maximized"
decorations = "none"

[font]
size = 24
italic = { style = "Regular" }
bold_italic = { style = "Bold" }

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullScreen"

[general]
import = ["~/.config/alacritty/current_theme.toml"]
